name: 💡 Idea / Brainstorm
description: Share early ideas or "what if we…" thoughts
title: "[Idea]: "
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        Got a random idea? Throw it out here! No idea is too wild.

  - type: textarea
    id: idea
    attributes:
      label: The idea
      description: What's the idea? Don't worry about details—just share the concept!
      placeholder: "Example: What if we could vote on which game to play next week?"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why this would be fun or useful
      description: What would make this cool or helpful?
      placeholder: "Example: It would save time in the group chat and make sure we play what most people want"
    validations:
      required: false
